// Your existing content here...

(${attack.searchKeywords.slice(0, 3).map((term: string) => `"${term}"`).join(' OR ')}) AND (cybersecurity OR "cyber attack" OR "security breach" OR "data breach" OR hacking OR malware OR vulnerability OR exploit)

// Rest of your existing content here...