name: Generate Daily Content

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 12 * * *" # Runs at 12:00 PM UTC every day

jobs:
  generate-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push commits

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run content generator
        run: npm run generate --prefix packages/generator
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add content/

          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "chore: Generate daily content for $(date +'%Y-%m-%d')"
            git push
          else
            echo "No new content generated. Nothing to commit."
          fi
